version: '3.3'

services:

  cpp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "cpp"
    volumes:
      - ./data:/home/my_user/Documents/
    
    stdin_open: true
    tty: true
    command: /bin/bash
  

